# Generated by Django 5.1.7 on 2025-03-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='link_id_imagekit',
            field=models.CharField(blank=True, default='', max_length=355, null=True),
        ),
    ]
