# Generated by Django 5.1.7 on 2025-03-19 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default='', max_length=255)),
                ('lastname', models.CharField(blank=True, default='', max_length=255)),
                ('gender', models.CharField(blank=True, default='', max_length=75)),
                ('age', models.IntegerField(null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, default='', max_length=255)),
                ('profile_photo', models.URLField(default='', verbose_name='File URL')),
                ('cover_photo', models.URLField(blank=True, default='', verbose_name='File URL')),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('auth_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
