# Generated by Django 5.1.7 on 2025-03-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cover_photo_id_imagekit',
            field=models.CharField(blank=True, default='', max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_photo_id_imagekit',
            field=models.CharField(blank=True, default='', max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ui_appearance',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='auth_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
