# Generated by Django 5.1.7 on 2025-05-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='File URL'),
        ),
    ]
